version: "3.9"
services:
  postgres:
    image: postgres:11.14-bullseye
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
  pgAdmin:
    image: dpage/pgadmin4:6.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=1
    volumes:
      - ./docker-data/pgAdmin:/var/lib/pgadmin
    ports:
      - 8080:80
  seq:
    image: datalust/seq:2021.4
    environment:
      - ACCEPT_EULA=y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=FJxdXvbAjqGUaflQ3WkOgdcUjCn4BzaoVjwfI3ddkZPel5QZRw==
    ports:
      - 8081:80
      - 5341:5341